name: Heroku-deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    # Run jobs for every PR
    # branches: '*'
    types: [opened, synchronize]

env:
  # NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  NODE_ENGINE: '14.17.1'

jobs:

  # This is to only deploy the last running workflow, in case there are more than one running at the 
  # same time.
  avoid_redundancy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

  test:
    uses: alexisromagnoli/pokedex-for-ci/.github/workflows/common.yml@main
    with: 
      # node-engine: "${{env.NODE_ENGINE}}"
      node-engine: "14.17.1"

  deploy:
    #needs: [test, e2e]
    needs: [test]
    runs-on: ubuntu-22.04
    # environment: 
    #   production
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy to Heroku
        if: ${{ github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}
          healthcheck: "https://${{secrets.HEROKU_APP}}.herokuapp.com/health"
          rollbackonhealthcheckfailed: true

